config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'

  resources :gossips
  # get '/gossips/new'   new_gossip_path

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user, required: false

	validates :title, presence: true, uniqueness: true
	validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :code

	validates :code, on: :create, presence: true, inclusion: { in: ["promo"]}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gossips
  validates :pseudo, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :sanitze_devise_params, if: :devise_controller?
	before_action :configure_permitted_parameters, if: :devise_controller?

	def sanitze_devise_params
		devise_parameter_sanitizer.permit(:sign_up, keys: [:pseudo])
	end

	def configure_permitted_parameters
	    # devise_parameter_sanitizer.for(:sign_up) { |u| u.permit( 
	        # :sign_up_code
	    # ) }
	end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	
	def index
	end
	
	def create
		mon_gossip = Gossip.new(title: params[:title], content: params[:content], user_id: current_user.id)
		if mon_gossip.save
			redirect_to root_path
		else
			redirect_to gossips_path
		end
	end

	def destroy
		@gossip = Gossip.find(params[:id])
	  	@gossip.destroy
		redirect_to root_path
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  	@tab_users = User.all.reverse
  	@tab_gossip = Gossip.all.reverse
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/gossips/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Creer un gossip</title>
</head>
<body>
	<div class="jumbotron">
		<h1>Crée un gossip :)</h1>

		<form action="/gossips" method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

			<label>Titre: </label>
			<input type="text" name="title" class="form-control">
			
			<label>Contenu: </label>
			<input type="text" name="content" class="form-control">

			<br>
			<input type="submit" name="create" value="Create">
		</form>
	</div>	

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SiteDevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

  </head>

  <body>
    <header>
    <nav class="nav nav-pills nav-fill">

      <a class="nav-item nav-link active" href="/">Accueil</a>
      <% if user_signed_in? %>
        <%= link_to "Edit Profil", edit_user_registration_path, class: "nav-item nav-link bg" %>
        <%= link_to "Log out", destroy_user_session_path , method: :delete, class: "nav-link nav-item bg-danger" %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class: "nav-item nav-link" %>
        <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link" %>
      <% end %>
    </nav>
  </header>

    <%= yield %>
    
  </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HOME</title>
</head>
<body>

	<div class="jumbotron">
		<% if !user_signed_in? %>
			<h1>Connecte toi bon sang !</h1>
			<%= link_to "Se login", new_user_session_path, class: "btn btn-lg btn-primary" %>
			<%= link_to "S'inscrire", new_user_registration_path, class: "btn btn-lg btn-primary"%>
		<% else %>
			<h1>Ah [...] en faite ya rien à voir sur une page d'accueil</h1>
			<h2>A par les personnes déjà inscrite:</h2>
			<ul>
				<% @tab_users.each do |user| %>
					<li> <%= user.email %> </li>
				<% end %>
			</ul>
		<% end %>

	</div>

	<h1> <a href="/gossips">Create Gossips</a> </h1>
	<% if user_signed_in? %>
		<h2>GOSSIP:</h2>
		<% @tab_gossip.each do |gossip| %>
			<ul>
				<li> 
					<%= "#{gossip.user.pseudo} : "%> <strong> <%= gossip.content %> </strong>
					<% if user_signed_in? && current_user.id == gossip.user_id %>
						<%= link_to "DELETE", gossip_path(gossip.id), class: "btn btn-xs btn-danger", :method => :delete %>
					<% end %>
				</li>
			</ul>
		<% end %>
	<% end %>

</body>
</html>